#!/usr/bin/env python

import sys
import logging
import fastspell.fastspell as fastspell

def main(argv):
    try:
        fastspell.logging_setup()
        args = fastspell.initialization()
        fastspell.main(args)
    except Exception as es:
        tb = traceback.format_exc()
        logging.error(tb)
        sys.exit(1)

if __name__=="__main__":
    main(sys.argv[1:])