#!/usr/bin/env python

import sys
import logging
import fastspell.pyfastspell as pyfastspell


def main(argv):
    try:
        pyfastspell.logging_setup()
        args = pyfastspell.initialization()
        pyfastspell.main(args)
    except Exception as es:
        tb = traceback.format_exc()
        logging.error(tb)
        sys.exit(1)

if __name__=="__main__":
    main(sys.argv[1:])