name: Build and upload to PyPI

on:
  push:
      branches:
          - "main"
  pull_request:
  release:
    types:
      - published

jobs:
  test:
    name: Run regression tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Run tests
        run: |-
          sudo apt-get -y install autopoint 
          pip install .
          python -m unittest discover -s tests

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          name: sdist
          path: dist/fastspell-*.tar.gz

  build_wheels:
    name: Build wheels
    runs-on: ubuntu-latest
    # name: Build wheels on ${{ matrix.os }}
    # runs-on: ${{ matrix.os }}
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-2019, macos-13]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Build wheels
        run: python -m pip wheel --no-deps -w wheelhouse .

    #   - name: Install cibuildwheel
    #     run: python -m pip install cibuildwheel==2.12.0

    #   - name: Build wheels
    #     run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse/fastspell-*.whl

  upload_pypi:
    needs: [test, build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v4.1.7
        with:
          name: wheels
          path: dist

      - uses: actions/download-artifact@v4.1.7
        with:
          name: sdist
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
